server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: rootroot
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost
    password: 123456
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  profiles:
    active: dev
mybatis:
  mapping-locations: classpath:mapping/*.xml
  type-aliases-package: com.example.demo.domain